version: '2'

services:
  otel-test-elastic:
    container_name: otel-test-elastic
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1G -Xms1G"
      #ELASTIC_PASSWORD: changeme
    networks:
      - elk
      - test-net

  otel-test-kibana:
    container_name: otel-test-kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - ./kibana/data:/usr/share/kibana/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5601:5601"
    networks:
      - elk
      - test-net
    depends_on:
      - otel-test-elastic
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector/config/collector.yml:/etc/otelcol-contrib/config.yaml
    ports:
      # OpenTelemetry 수신포트
      - 4317:4317 # gRPC receiver
      - 4318:4318 # http receiver

      # Collector Health Check 포트
      - 13133:13133 # health check

      # OpenTelemetry 성능체크
      - 55679:55679 # zpages ext (디버깅 페이지)
      - 1888:1888 # pprof ext (otel 성능 체크)

      # Prometheus 연동
      - 8888:8888
      - 8889:8889


networks:

  elk:
    driver: bridge

  test-net:
    external: true