version: '3'

services:
  otel-test-fe:
    container_name: otel-test-fe
    image: imwaffle/otel-test-be:latest
    env_file: ./fe.env
    networks:
      - test-net
    ports:
      - "800:80"
    depends_on:
      - otel-test-be

  otel-test-be:
    container_name: otel-test-be
    image: imwaffle/otel-test-fe:latest
    env_file: ./be.env
    networks:
      - test-net
    ports:
      - "8080:8080"

networks:
  test-net:
    external: true
